language: java
jdk:
  - oraclejdk8
  - oraclejdk9
env:
  # There are actually significant differences with respect to JMX in recent fix packs
  - WEBSPHERE_VERSION=8.5.5.10
  - WEBSPHERE_VERSION=8.5.5.13
  - WEBSPHERE_VERSION=9.0.0.8
install: true
script: "mvn verify -B -U"
cache:
  directories:
  - $HOME/.m2
